/*
 ADOBE CONFIDENTIAL
 ___________________

 Copyright 2012 Adobe Systems Incorporated
 All Rights Reserved.

 NOTICE:  All information contained herein is, and remains
 the property of Adobe Systems Incorporated and its suppliers,
 if any.  The intellectual and technical concepts contained
 herein are proprietary to Adobe Systems Incorporated and its
 suppliers and may be covered by U.S. and Foreign Patents,
 patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material
 is strictly forbidden unless prior written permission is obtained
 from Adobe Systems Incorporated.
*/
(function(b,c,a){a.Plugins.SlideShowCaptions={defaultOptions:{captionClassName:"SSSlideCaption"},initialize:function(a,c){var g=this;b.extend(c,b.extend({},g.defaultOptions,c));a.bind("attach-behavior",function(){g._attachBehavior(a)})},_attachBehavior:function(a){var b=a._findWidgetElements("."+a.options.captionClassName);if(b.length)a._sscpCaptions=b,b.css("display","none"),a.slides.bind("wp-panel-show",function(a,c){b.eq(c.panelIndex).css("display","block")}),a.slides.bind("wp-panel-hide",function(a,
c){b.eq(c.panelIndex).css("display","none")}),a.bind("ready",function(){b.eq(a.slides.activeIndex).css("display","block")})}};a.Plugins.SlideShowLabel={defaultOptions:{labelClassName:"SlideShowLabel"},initialize:function(a,c){var g=this;b.extend(c,b.extend({},g.defaultOptions,c));a.bind("attach-behavior",function(){g._attachBehavior(a)})},_attachBehavior:function(a){var b=this,c=a._findWidgetElements("."+a.options.labelClassName);if(c.length)a._$sslpLabels=c,a.slides.bind("wp-panel-show",function(){b._updateLabels(a)}),
a.bind("ready",function(){b._updateLabels(a)})},_findAllTextNodes:function(a,b){b=b||[];switch(a.nodeType){case 3:b.push(a);break;case 1:if(a.nodeName.toLowerCase()!=="script")for(var c=a.firstChild;c;)this._findAllTextNodes(c,b),c=c.nextSibling}a.nextSibling&&this._findAllTextNodes(a.nextSibling,b);return b},_updateLabels:function(a){var b=this,c=a.slides,h=c.activeIndex+1,j=c.$element.length;a._$sslpLabels.each(function(){for(var a=b._findAllTextNodes(this),c=a.length,d=0,g=function(a){return++d===
1?h:d===2?j:a},o=0;o<c;o++){var n=a[o],p=n.nodeValue,q=p.replace(/\d+/g,g);if(q!==p)n.nodeValue=q}})}};a.Plugins.Lightbox={defaultOptions:{lightboxPartsSelector:".PamphletLightboxPart",closeBtnClassName:"PamphletCloseButton"},initialize:function(a,c){var g=this;b.extend(c,b.extend({},g.defaultOptions,c));a._sslbpAutoPlay=c.autoPlay;c.autoPlay=!1;a.bind("before-transform-markup",function(){g._beforeTransformMarkup(a)});a.bind("attach-behavior",function(){g._attachBehavior(a)})},_beforeTransformMarkup:function(b){b._sslbpShownInitially=
!0;var c=b._findWidgetElements("."+b.options.slideClassName);if(c.filter(":hidden").length==0)b._sslbpSlideOffset=c.offset();else{b._sslbpShownInitially=!1;var g=b._findWidgetElements("."+b.options.viewClassName);b._sslbpSlideOffset={top:a.Utils.getCSSIntValue(g,"top")+a.Utils.getCSSIntValue(c,"top"),left:a.Utils.getCSSIntValue(g,"left")+a.Utils.getCSSIntValue(c,"left")}}},_attachBehavior:function(a){var b=this,c=a.options;a.tabs.$element.bind(c.event,function(){b._openLightbox(a)});a.slides.bind("wp-panel-before-show",
function(){b._openLightbox(a)});a._$sslbpCloseBtn=a._findWidgetElements("."+c.closeBtnClassName).bind("click",function(){b._closeLightbox(a)});b._initializeMarkup(a)},_initializeMarkup:function(c){var f=c.options,g=c._findWidgetElements("."+f.viewClassName),h=c.slides.$element,j=g,i=c._sslbpSlideOffset,k=h.outerWidth(),m=h.outerHeight(),l=c._findWidgetElements(f.lightboxPartsSelector),j=b(g[0].parentNode).filter("."+f.clipClassName);j.length===0&&(j=g);l.each(function(f,g){var h=b(g),j=c._sslbpShownInitially?
h.offset():{top:a.Utils.getCSSIntValue(h,"top"),left:a.Utils.getCSSIntValue(h,"left")};h.css({left:j.left-i.left,top:j.top-i.top})}).addClass("popup_element");var o=b('<div id="'+(g.attr("id")||"")+'"></div>').css({left:0,top:0,width:"auto",height:"auto",padding:0,margin:0,zIndex:"auto"});g.removeAttr("id");var n=b("<div class='overlayWedge'></div>").insertBefore(h[0]);o.append(g.children().not("."+f.slideClassName));g.append(h);o.css({visibility:"hidden"}).appendTo(document.body);var g=o.outerWidth(),
p=o.outerHeight();o.detach().css({visibility:""});j.css({padding:0,left:0,top:0,width:k,height:m,borderWidth:0,background:"none",position:"absolute"});f.transitionStyle==="fading"&&h.css({left:0,top:0,position:"absolute"});f=-k/2;m=-m/2;j=b("<div class='LightboxContent'></div>").css({position:"absolute"}).append(j).append(l).museOverlay({autoOpen:!1,offsetLeft:f,offsetTop:m,overlayExtraWidth:g,overlayExtraHeight:p,$overlaySlice:o,$overlayWedge:n,onClose:function(){c.stop()}});if(b.browser.msie&&b.browser.version<
9){var q=o[0];a.Utils.needPIE(function(){PIE.detach(q);PIE.attach(q)})}c._$sslbpOverlay=j;c._csspIsImageSlideShow||h.each(function(){a.Utils.detachIframesAndObjectsToPauseMedia(b(this))})},_openLightbox:function(c){var f=c._$sslbpOverlay;f.data("museOverlay").isOpen||(f.museOverlay("open"),c._sslbpAutoPlay&&c.play());c._csspIsImageSlideShow||a.Utils.attachIframesAndObjectsToResumeMedia(b(c.slides.activeElement))},_closeLightbox:function(c){c._$sslbpOverlay.data("museOverlay").isOpen&&(c.stop(),c._$sslbpOverlay.museOverlay("close"),
c._csspIsImageSlideShow||a.Utils.detachIframesAndObjectsToPauseMedia(b(c.slides.activeElement)))}};a.Plugins.ContentSlideShow={defaultOptions:{displayInterval:3E3,transitionDuration:500,transitionStyle:"fading",contentLayout_runtime:"stack",event:"click",deactivationEvent:"none",hideAllContentsFirst:!1,shuffle:!1},slideShowOverrides:{slideshowClassName:"SlideShowWidget",viewClassName:"SlideShowContentPanel",slideClassName:"SSSlide",slideLinksClassName:"SSSlideLinks",slideLinkClassName:"SSSlideLink",
slideLinkActiveClassName:"SSSlideLinkSelected",slideCountClassName:"SSSlideCount",firstBtnClassName:"SSFirstButton",lastBtnClassName:"SSLastButton",prevBtnClassName:"SSPreviousButton",nextBtnClassName:"SSNextButton",playBtnClassName:"SSPlayButton",stopBtnClassName:"SSStopButton",closeBtnClassName:"SSCloseButton",heroFitting:"fitContentProportionally",thumbFitting:"fillFrameProportionally",lightboxPartsSelector:".SlideShowCaptionPanel, .SSFirstButton, .SSPreviousButton, .SSNextButton, .SSLastButton, .SlideShowLabel, .SSCloseButton",
lightboxEnabled_runtime:!1},compositionOverrides:{slideshowClassName:"PamphletWidget",viewClassName:"ContainerGroup",slideClassName:"Container",slideLinkClassName:"Thumb",slideLinkActiveClassName:"PamphletThumbSelected",prevBtnClassName:"PamphletPrevButton",nextBtnClassName:"PamphletNextButton",lightboxPartsSelector:".PamphletLightboxPart"},initialize:function(d,f){var g=this,h=d.$element.hasClass("SlideShowWidget"),j=h?g.slideShowOverrides:g.compositionOverrides;d._csspIsImageSlideShow=h;d._csspIsDynamicSlideshow=
h&&d.$element.parent().hasClass("mu-query");b.extend(f,b.extend({},g.defaultOptions,j,f));if(f.hideAllContentsFirst)f.defaultIndex=-1;if(f.lightboxEnabled_runtime)f.contentLayout_runtime="lightbox";h&&(c.Widget.ContentSlideShow.slideImageIncludePlugin.initialize(d,f),a.Plugins.SlideShowLabel.initialize(d,f),a.Plugins.SlideShowCaptions.initialize(d,f));f.transitionStyle=="fading"?c.Widget.ContentSlideShow.fadingTransitionPlugin.initialize(d,f):a.Browser.Features.Touch&&a.Browser.Features.Touch.Start==
"touchstart"&&f.enableSwipe===!0?c.Widget.ContentSlideShow.swipeTransitionPlugin.initialize(d,f):c.Widget.ContentSlideShow.filmstripTransitionPlugin.initialize(d,f);f.contentLayout_runtime==="lightbox"&&a.Plugins.Lightbox.initialize(d,f);f.shuffle===!0&&c.Widget.ContentSlideShow.shufflePlayPlugin.initialize(d,f);d.bind("transform-markup",function(){g._transformMarkup(d)});d.bind("attach-behavior",function(){g._attachBehavior(d)})},_transformMarkup:function(a){var c=a.options,g=a._findWidgetElements("."+
c.viewClassName);if(c.transitionStyle!=="fading"){var h=b('<div class="'+c.clipClassName+'"/>'),j=a._findWidgetElements("."+c.slideClassName),c=j.outerWidth(),j=j.outerHeight(),i={position:"relative",width:c+"px",height:j+"px",overflow:"hidden"};if(g.css("position")==="absolute")i.position="absolute",i.left=g.css("left"),i.top=g.css("top");h.css(i);g.css({position:"relative",top:"0",left:"0",width:c+"px",height:j+"px",margin:"0",padding:"0",overflow:"hidden"}).wrap(h)}else g.css({width:"0",height:"0"});
a._csspIsDynamicSlideshow&&this._layoutThumbs(a)},_attachBehavior:function(c){var f=c.options,g=c.tabs,h=c.slides.$element,j=f.slideLinkActiveClassName;c._csspIsDynamicSlideshow&&(this._setupImagePositioning(c,c.slides.$element,f.heroFitting),this._setupImagePositioning(c,c.tabs.$element,f.thumbFitting));if(g&&(f.event==="mouseover"||f.event==="mouseover_canRollout")){var i=g.$element,k=this._hitTest;i.bind("mouseenter",function(){var a=b(this),j=i.index(a);g.selectTab(j);if(f.deactivationEvent===
"mouseout_trigger"||f.deactivationEvent==="mouseout_both"){var o=h.eq(j),n=function(g){var h=k(g,a);f.deactivationEvent==="mouseout_both"&&(h=h||k(g,o));h||(b(document).unbind("mousemove",n),c.slides.hidePanel(j))};b(document).bind("mousemove",n)}})}g&&j&&(f.hideAllContentsFirst||g.$element.eq(g.options.defaultIndex).addClass(j),c.slides.bind("wp-panel-show",function(a,b){g.$element.eq(b.panelIndex).addClass(j)}).bind("wp-panel-hide",function(a,b){g.$element.eq(b.panelIndex).removeClass(j)}));this._attachStopOnClickHandler(c,
c.$firstBtn);this._attachStopOnClickHandler(c,c.$lastBtn);this._attachStopOnClickHandler(c,c.$previousBtn);this._attachStopOnClickHandler(c,c.$nextBtn);this._attachStopOnClickHandler(c,c.$playBtn);this._attachStopOnClickHandler(c,c.$stopBtn);g&&f.contentLayout_runtime!=="lightbox"&&this._attachStopOnClickHandler(c,g.$element);c._csspIsImageSlideShow||c.slides.bind("wp-panel-hide",function(c,d){a.Utils.detachIframesAndObjectsToPauseMedia(b(d.panel))}).bind("wp-panel-show",function(c,d){a.Utils.attachIframesAndObjectsToResumeMedia(b(d.panel))})},
_attachStopOnClickHandler:function(a,b){b.bind(a.options.event==="click"?"click":"mouseover",function(){a.stop()})},_hitTest:function(a,b){b.outerWidth()===0&&(b=b.children(".popup_anchor").children(".popup_element").eq(0));var c=b.offset(),c={x:c.left,y:c.top,width:b.outerWidth(),height:b.outerHeight()};return a.pageX>=c.x&&a.pageX<=c.x+c.width&&a.pageY>=c.y&&a.pageY<=c.y+c.height},_layoutThumbs:function(c){var f=c.options,g=a.Utils.getStyleValue;c._findWidgetElements("."+f.slideLinksClassName).each(function(){var c=
b(this).find("."+f.slideLinkClassName);firstThumb=c[0];tWidth=g(firstThumb,"width");tHeight=g(firstThumb,"height");gapH=g(firstThumb,"margin-right");gapV=g(firstThumb,"margin-bottom");borderL=g(firstThumb,"border-left-width");borderR=g(firstThumb,"border-right-width");borderT=g(firstThumb,"border-top-width");borderB=g(firstThumb,"border-bottom-width");gWidth=g(this,"width");paddingL=g(this,"padding-left");paddingT=g(this,"padding-top");maxNumThumb=Math.floor((gWidth+gapH)/(tWidth+borderL+borderR+
gapH));gStyle=this.runtimeStyle?this.runtimeStyle:this.style;numRow=Math.ceil(c.length/maxNumThumb);firstRowNum=c.length<maxNumThumb?c.length:maxNumThumb;leftPos=leftMostPos=a.Utils.pixelRound((gWidth-(tWidth+borderL+borderR)*firstRowNum-gapH*(firstRowNum-1))/2)+paddingL;topPos=paddingT;numInRow=1;gStyle.height=(tHeight+borderT+borderB)*numRow+gapV*(numRow-1)+"px";c.each(function(){numInRow>firstRowNum&&(numInRow=1,leftPos=leftMostPos,topPos+=tHeight+borderT+borderB+gapV);numInRow++>1&&(leftPos+=
tWidth+borderL+borderR+gapH);var a=this.runtimeStyle?this.runtimeStyle:this.style;a.marginRight="0px";a.marginBottom="0px";a.left=leftPos+"px";a.top=topPos+"px"})})},_setupImagePositioning:function(a,c,g){var h=this;c.each(function(){var a=this;b(a).find("img").each(function(){var c=this;c.complete?h._positionImage(c,a,g):b(c).load(function(){h._positionImage(c,a,g)})})})},_positionImage:function(b,c,g){var c=b.width,h=b.height,j=a.Utils.getNaturalWidth(b),i=a.Utils.getNaturalHeight(b);if(!(c==j&&
h==i)){var k=j,m=i;if(g=="fillFrameProportionally")j>c&&i>h&&(g=j/c,k=i/h,g<k?(m=i/g,k=c):(m=h,k=j/k));else if(g=="fitContentProportionally"&&(j>c||i>h))g=j/c,k=i/h,g>k?(m=i/g,k=j/g):(m=i/k,k=j/k);b=b.runtimeStyle?b.runtimeStyle:b.style;b.width=a.Utils.pixelRound(k)+"px";b.height=a.Utils.pixelRound(m)+"px";b.marginTop=a.Utils.pixelRound((h-m)/2)+"px";b.marginLeft=a.Utils.pixelRound((c-k)/2)+"px"}}};b.extend(c.Widget.ContentSlideShow.slideImageIncludePlugin.defaultOptions,{imageIncludeClassName:"ImageInclude",
slideLoadingClassName:"SSSlideLoading"});c.Widget.ContentSlideShow.prototype.defaultPlugins=[a.Plugins.ContentSlideShow]})(jQuery,WebPro,Muse,window);
